smiles-columns = [Drug]
num-workers = 0
batch-size = 32
accelerator = gpu
devices = 1
use-molformer-1d = true
molformer-model = D:\code\duomotai\chem5090\hf_models\MoLFormer-XL-both-10pct
molformer-cache-dir = D:\code\duomotai\chem5090\chemprop\data\newdata\molformer_1d_cache
molformer-device = cpu
molformer-max-length = 256
molformer-pooling = pooler
molformer-batch-size = 32
use-gotennet-3d-graph = true
geometry-cache-dir = D:\code\duomotai\chem5090\chemprop\data\newdata\gotennet_3d_cache
geometry-num-conformers = 8
data-path = D:\code\duomotai\chem5090\chemprop\data\newdata\tdc_admet_group_merged_3d\bbb_martins\seed_1.csv
output-dir = D:\code\duomotai\chem5090\chemprop\data\newdata\hpo20_cls\classification\bbb_martins\hpo\fusion_1d2d3d_embedding_xattn_molformer_gotennet\trial_0007\seed_1
message-hidden-dim = 600
depth = 3
dropout = 0.30000000000000004
ffn-hidden-dim = 300
ffn-num-layers = 2
x-d-encoder = embedding-xattn
x-d-embed-dim = 128
x-d-encoder-heads = 4
x-d-fp-groups = 128
x-d-fp-encoder = itransformer
gotennet-cutoff = 4.0
gotennet-pooling = mean_max
gotennet-lr-scale = 0.1
target-columns = [Y]
splits-column = split
task-type = classification
metrics = [roc, prc, accuracy]
show-individual-scores = true
warmup-epochs = 2
init-lr = 1.1353451907699788e-05
max-lr = 0.00012839847326348127
final-lr = 1.3304215578499564e-05
epochs = 40
patience = 10
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
mace-model = medium
mace-device = cpu
mace-dtype = float32
mace-fmax = 0.03
frzn-ffn-layers = 0
ensemble-size = 1
aggregation = norm
aggregation-norm = 100
motif-2d-depth = 2
motif-2d-fusion = eca
motif-2d-residual-scale = 0.1
hignn-slices = 2
activation = RELU
x-d-encoder-layers = 2
x-d-patch-size = 128
molformer-unfreeze-layers = 0
molformer-lr-scale = 0.05
x-d-3d-dim = 0
x-3d-pooler = graph_transformer
multiclass-num-classes = 3
atom-ffn-hidden-dim = 300
atom-ffn-num-layers = 1
atom-multiclass-num-classes = 3
bond-ffn-hidden-dim = 300
bond-ffn-num-layers = 1
bond-multiclass-num-classes = 3
atom-constrainer-ffn-hidden-dim = 300
atom-constrainer-ffn-num-layers = 1
bond-constrainer-ffn-hidden-dim = 300
bond-constrainer-ffn-num-layers = 1
v-kl = 0.0
eps = 1e-08
alpha = 0.1
tracking-metric = val_loss
stage2-lr-scale = 0.1
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-replicates = 1
data-seed = 0
